### PR TITLE
Add support for instances to work with osTicket v1.17

### PR DESCRIPTION
**Pull request by JensEB**
osTicket v1.17 needs to select a plugin instance to find saved settings. This changes make this plugin compatible to osTicket v1.17

### CODE REVIEW

**Comment by ericbrun-73** [comment]
This commit for this pull request work for my with OsTicket 1.17.
Thank you !

**Comment by walaakongmai** [comment]
hi! may I know how to enable this plug in on osticket 1.17? it is looking for a phar file. sorry newbie here.

**Comment by JensEB** [comment]
No, you don't need a phar file. You can upload a folder into the plugins folder. Then you should to be able to install this plugin

**Comment by walaakongmai** [comment]
> No, you don't need a phar file. You can upload a folder into the plugins folder. Then you should to be able to install this plugin

Hi JensEB! Thanks ! I was able to activate the plug in. now I have another problem. I encountered an email notification saying that the slack is not configured and Slack posting issue. it says no URL then a link to my osticket webpage is included in the message.  what does this mean?  I already configured the webhook url in the plug in. and followed the steps. tried to restart  it and still to no avail. is this related to the instance I created? 

I am using windows 11 and xampp.

More power to you by the way!

**Pull request merged**
